// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwhhqtnhncanwictnxnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aGhxdG5obmNhbndpY3RueG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzM0MjgsImV4cCI6MjA2NTU0OTQyOH0.Hg5yGjNwmwcZLSagk8T6tsQsz1W2ifH5ls4frsSw2AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);